export {
  ApiError,
  createApiClient,
  type ApiClient,
  type ApiClientOptions,
  type Experience,
  type Proficiency,
  type Profile,
  type ProjectDetail,
  type ProjectMetric,
  type ProjectSummary,
  type RequestOptions,
  type Skill,
  type SkillCategory,
  type SocialLink,
  type SocialPlatform,
  type Technology,
  type TechnologyCategory,
} from './client';
