export {
  ApiError,
  createApiClient,
  type ApiClient,
  type ApiClientOptions,
  type ContactSubmission,
  type Experience,
  type GitHubStats,
  type LanguageShare,
  type Proficiency,
  type Profile,
  type ProjectDetail,
  type ProjectMetric,
  type ProjectSummary,
  type Repository,
  type RequestOptions,
  type Skill,
  type SkillCategory,
  type SocialLink,
  type SocialPlatform,
  type Technology,
  type TechnologyCategory,
} from './client';
